name: Validate Black Formatting

on:
  workflow_call:
    inputs:
      black-version:
        required: false
        type: string
        default: "22.3.0"
  workflow_dispatch:
  push:
    paths:
      - "**.py"

jobs:
  format:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python3 -m pip install black~=${{ inputs.black-version }}

      - name: Check Black formatting
        run: black --check .
